# Generated by Django 3.2.7 on 2021-09-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_quiz_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=' ', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
