# Generated by Django 3.2.7 on 2021-09-26 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
